apiVersion: v2
name: diz-in-a-box
type: application
description: Datenintegrationszentrum in einer Box.
deprecated: false
kubeVersion: ">= 1.21.0"
dependencies:
  - name: akhq
    condition: akhq.enabled
    repository: https://akhq.io/
    version: 0.3.1
  - condition: stream-processors.enabled
    name: stream-processors
    repository: https://miracum.github.io/charts
    version: 1.1.9
  - condition: hapi-fhir-jpaserver.enabled
    name: hapi-fhir-jpaserver
    repository: https://hapifhir.github.io/hapi-fhir-jpaserver-starter
    version: 0.11.0
# x-release-please-start-version
version: 0.1.0
appVersion: 0.1.0
# x-release-please-end-version
