apiVersion: v2
name: diz-in-a-box
type: application
description: DIZ in a box.
deprecated: false
kubeVersion: ">= 1.21.0"
dependencies:
  - name: akhq
    condition: akhq.enabled
    repository: https://akhq.io/
    version: 0.3.1
  - condition: stream-processors.enabled
    name: stream-processors
    repository: https://miracum.github.io/charts
    version: 1.1.10
  - condition: hapi-fhir-jpaserver.enabled
    name: hapi-fhir-jpaserver
    repository: https://hapifhir.github.io/hapi-fhir-jpaserver-starter
    version: 0.11.1
  - condition: fhir-gateway.enabled
    name: fhir-gateway
    repository: https://miracum.github.io/charts
    version: 6.0.3
# x-release-please-start-version
version: 1.0.0
appVersion: 1.0.0
# x-release-please-end-version
