services:
  decompose-xmls:
    build:
      context: .
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      KAFKA_ENABLED: "true"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_OUTPUT_TOPIC: "onkostar.MELDUNG_EXPORT"
      SAVE_AS_FILES_ENABLED: "true"
    volumes:
      - ./input-obds-reports:/app/input-obds-reports
      - ./output-obds-reports:/app/output-files
