apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: bzkf-dizbox-cluster
spec:
  kafka:
    version: 3.3.1
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    resources:
      limits:
        memory: 3Gi
    jvmOptions:
      -Xms: 2048m
      -Xmx: 2048m
    storage:
      type: persistent-claim
      size: 64Gi
  zookeeper:
    replicas: 1
    resources:
      limits:
        memory: 2Gi
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
    storage:
      type: persistent-claim
      size: 24Gi
  entityOperator:
    userOperator: {}
