apiVersion: v2
name: prerequisites
type: application
description: Prerequisites for DIZ in a box.
deprecated: false
kubeVersion: ">= 1.21.0"
dependencies:
  - name: strimzi-kafka-operator
    repository: https://strimzi.io/charts/
    version: 0.35.1
# x-release-please-start-version
version: 1.5.9
appVersion: 1.5.9
# x-release-please-end-version
