strimzi-kafka-operator:
  image:
    tag: 0.34.0@sha256:1cdeda55d10793c1de487469e22a2e46d2d348ff54d1d998ac03df8c5c1ef937
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    privileged: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault

  extraEnvs:
    # see <https://strimzi.io/blog/2022/09/09/configuring-security-context-in-pods-managed-by-strimzi/>
    - name: STRIMZI_POD_SECURITY_PROVIDER_CLASS
      value: restricted
