services:
  obds-to-fhir:
    image: ghcr.io/miracum/obds-to-fhir:v2.0.7
    restart: unless-stopped
    cap_drop:
      - ALL
    privileged: false
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    user: "65532:65532"
    environment:
      SECURITY_PROTOCOL: PLAINTEXT
      BOOTSTRAP_SERVERS: kafka:9092
      FHIR_OUTPUT_TOPIC_PARTITION_COUNT: "1"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_MINPARTITIONCOUNT: "1"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_AUTOADDPARTITIONS: "true"
      NUM_STREAM_THREADS: "1"
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75"
      ACTIVE_PROFILE: "patient"
      YEAR_LIMITATION_SUFFIX: "" # e.g. ".2023"
      FHIR_SYSTEMS_PATIENTID: "https://CHANGE-ME/patid"
      FHIR_SYSTEMS_CONDITIONID: "https://CHANGE-ME/patid"
      FHIR_SYSTEMS_OBSERVATIONID: "https://CHANGE-ME/patid"
      FHIR_SYSTEMS_PROCEDUREID: "https://CHANGE-ME/patid"
      FHIR_SYSTEMS_MEDICATIONSTATEMENTID: "https://CHANGE-ME/patid"
