services:
  onkoadt-to-fhir:
    image: harbor.miracum.org/streams-ume/onkoadt-to-fhir:v1.10.0@sha256:e584922155db6e8c281a9b7fc3728701d0f08f0713ebd35c9931492a761c003a
    restart: unless-stopped
    cap_drop:
      - ALL
    privileged: false
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    user: "65532:65532"
    environment:
      SECURITY_PROTOCOL: PLAINTEXT
      BOOTSTRAP_SERVERS: kafka:9092
      FHIR_OUTPUT_TOPIC_PARTITION_COUNT: "1"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_MINPARTITIONCOUNT: "1"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_AUTOADDPARTITIONS: "true"
      NUM_STREAM_THREADS: "1"
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75"
