services:
  obds-to-fhir:
    image: ghcr.io/miracum/obds-to-fhir:v2.0.15@sha256:c359ef5449068ff0c1231c3ee237801f2fb76932ab9a16386813d02c07ac9f7d
    restart: unless-stopped
    cap_drop:
      - ALL
    privileged: false
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    user: "65532:65532"
    environment:
      SECURITY_PROTOCOL: PLAINTEXT
      BOOTSTRAP_SERVERS: kafka:9092
      FHIR_OUTPUT_TOPIC_PARTITION_COUNT: "1"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_MINPARTITIONCOUNT: "1"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_AUTOADDPARTITIONS: "true"
      NUM_STREAM_THREADS: "1"
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75"
      ACTIVE_PROFILE: "patient"
      YEAR_LIMITATION_SUFFIX: "" # e.g. ".2023"
      FHIR_SYSTEMS_PATIENTID: ${FHIR_SYSTEMS_PATIENTID:-https://fhir.diz.uk-erlangen.de/identifiers/patient-id}
      FHIR_SYSTEMS_CONDITIONID: ${FHIR_SYSTEMS_CONDITIONID:-https://fhir.diz.uk-erlangen.de/identifiers/onkostar-xml-condition-id}
      FHIR_SYSTEMS_OBSERVATIONID: ${FHIR_SYSTEMS_OBSERVATIONID:-https://fhir.diz.uk-erlangen.de/identifiers/onkostar-xml-observation-id}
      FHIR_SYSTEMS_PROCEDUREID: ${FHIR_SYSTEMS_PROCEDUREID:-https://fhir.diz.uk-erlangen.de/identifiers/onkostar-xml-procedure-id}
      FHIR_SYSTEMS_MEDICATIONSTATEMENTID: ${FHIR_SYSTEMS_MEDICATIONSTATEMENTID:-https://fhir.diz.uk-erlangen.de/identifiers/onkostar-xml-medication-statement-id}
