services:
  adt-fhir-to-opal:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OUTPUT_FOLDER: "/home/jovyan/opal-output"
      KAFKA_TOPIC_YEAR: "2023"
      KAFKA_BOOTSTRAP_SERVER: "kafka:9092"
      KAFKA_PATIENT_TOPIC: "fhir.onkoadt.Patient."
      KAFKA_CONDITION_TOPIC: "fhir.onkoadt.Condition."
      KAFKA_OBSERVATION_TOPIC: "fhir.onkoadt.Observation."
      KAFKA_PROCEDURE_TOPIC: "fhir.onkoadt.Procedure."
      KAFKA_MEDICATIONSTATEMENT_TOPIC: "fhir.onkoadt.MedicationStatement."
    volumes:
      - ${PWD}/output:/home/jovyan/opal-output
