apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ include "onco-analytics-on-fhir.fullname" . }}-akhq
  labels:
    {{- include "onco-analytics-on-fhir.labels" . | nindent 4 }}
    strimzi.io/cluster: {{ index .Values "stream-processors" "strimziClusterName" }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  authentication:
    type: tls
