name: ci

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  release:
    types: [created]

permissions: read-all

jobs:
  k3s:
    runs-on: ubuntu-22.04
    env:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    steps:
      - name: Install k3s
        env:
          K3S_KUBECONFIG_MODE: 644
        run: |
          curl -sfL https://get.k3s.io | sh -

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Install dependencies
        run: |
          kubectl get node

          # TODO: dedicated namespaces
          helm repo add strimzi https://strimzi.io/charts/
          helm install strimzi-kafka-operator strimzi/strimzi-kafka-operator

          kubectl apply -f k8s/kafka-cluster.yaml
          kubectl wait kafka/bzkf-dizbox-cluster --for=condition=Ready --timeout=300s

          kubectl get all -A

      - name: Install diz-in-a-box
        run: |
          helm repo add miracum https://miracum.github.io/charts
          helm repo add akhq https://akhq.io/
          helm repo add hapi-fhir-jpaserver-starter https://hapifhir.github.io/hapi-fhir-jpaserver-starter

          helm dependency build charts/diz-in-a-box
          helm upgrade --install diz-in-a-box charts/diz-in-a-box

          kubectl get all -A
