name: release-please

on:
  push:
    branches:
      - master

permissions: read-all

jobs:
  release-please:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@f7edb9e61420a022c0f1123edaf342d7e127df92 # v3.7.7
        with:
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
          release-type: simple
          pull-request-title-pattern: "chore: release ${version}"
          extra-files: |
            charts/diz-in-a-box/Chart.yaml
            README.md
          changelog-types: |
            [
              { "type": "feat", "section": "Features" },
              { "type": "fix", "section": "Bug Fixes" },
              { "type": "perf", "section": "Performance Improvements" },
              { "type": "docs", "section": "Documentation", "hidden": false },
              {
                "type": "chore",
                "section": "Miscellaneous Chores",
                "hidden": false
              },
              { "type": "build", "section": "Build", "hidden": false },
              { "type": "ci", "section": "CI/CD", "hidden": false }
            ]
