name: scheduled

on:
  repository_dispatch: {}
  workflow_dispatch: {}
  schedule:
    - cron: "00 18 * * *"

permissions: read-all

jobs:
  schedule:
    uses: miracum/.github/.github/workflows/standard-schedule.yaml@af38234ff7a38994a6e414ba2f13a1576eed54c0 # v1.4.1
    permissions:
      contents: read
      issues: write
      security-events: write
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
